
eureka:
  client:
    serviceUrl:
      defaultZone: http://10.46.225.131:8001/eureka

sso:
  url: https://passport-pre.abcfintech.com
  verifyToken:
    url: /sso/verifyToken
    method: post

searchLogPath: logs/searchLog.log